import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, NavLink } from 'react-router-dom';
export function Shell({ title, subtitle, navigation, children, }) {
    return (_jsx("div", { className: "min-h-screen bg-[radial-gradient(circle_at_top_left,_rgba(251,191,36,0.18),_transparent_25%),radial-gradient(circle_at_bottom_right,_rgba(14,165,233,0.16),_transparent_22%),linear-gradient(180deg,_#020617_0%,_#0f172a_100%)] text-slate-50", children: _jsxs("div", { className: "grid min-h-screen lg:grid-cols-[280px_1fr]", children: [_jsxs("aside", { className: "border-b border-white/10 bg-slate-950/70 p-6 backdrop-blur lg:border-b-0 lg:border-r", children: [_jsxs(Link, { className: "mb-10 flex items-center gap-3", to: "/", children: [_jsx("div", { className: "grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-amber-300 to-emerald-400 font-black text-slate-950", children: "SM" }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold tracking-wide", children: "SubFlow" }), _jsx("p", { className: "text-sm text-slate-400", children: "Subscription OS" })] })] }), _jsx("nav", { className: "grid gap-2", children: navigation.map((item) => (_jsx(NavLink, { to: item.to, className: ({ isActive }) => `rounded-2xl px-4 py-3 text-sm transition ${isActive
                                    ? 'bg-white/12 text-white shadow-lg shadow-slate-950/30'
                                    : 'text-slate-300 hover:bg-white/6 hover:text-white'}`, children: item.label }, item.to))) })] }), _jsxs("main", { className: "p-6 lg:p-8", children: [_jsx("header", { className: "mb-8 flex flex-col gap-3 md:flex-row md:items-end md:justify-between", children: _jsxs("div", { children: [_jsx("p", { className: "mb-2 text-xs uppercase tracking-[0.28em] text-amber-300", children: subtitle }), _jsx("h1", { className: "text-4xl font-black tracking-tight", children: title })] }) }), _jsx("section", { className: "grid gap-5 xl:grid-cols-12", children: children })] })] }) }));
}
export function MetricCard({ label, value, detail, }) {
    return (_jsxs("article", { className: "rounded-[28px] border border-white/10 bg-white/6 p-6 shadow-2xl shadow-slate-950/30 xl:col-span-4", children: [_jsx("p", { className: "text-sm text-slate-400", children: label }), _jsx("h3", { className: "mt-2 text-3xl font-black", children: value }), _jsx("p", { className: "mt-2 text-sm text-slate-300", children: detail })] }));
}
export function Surface({ title, actions, children, }) {
    return (_jsxs("article", { className: "rounded-[28px] border border-white/10 bg-white/6 p-6 shadow-2xl shadow-slate-950/30 xl:col-span-12", children: [_jsxs("div", { className: "mb-5 flex items-center justify-between gap-3", children: [_jsx("h2", { className: "text-2xl font-bold tracking-tight", children: title }), actions] }), children] }));
}
